version: '3.3'
volumes:
  mysql-db:
    driver: local
services:
  mysql:
    build: ../database/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: always
    environment:
      MYSQL_DATABASE: skillMgr
      MYSQL_USER: skillMgr
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    networks:
      - 'skill-mgr-system-net'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
  discovery:
    image: registry.kirin.mydns.jp/sun-project/discovery
    networks:
      - 'skill-mgr-system-net'
    ports:
      - '8761:8761'
  gateway:
    image: registry.kirin.mydns.jp/sun-project/gateway
    networks:
      - 'skill-mgr-system-net'
    ports:
      - '8080:8080'
  skill-mgr-api:
    image: registry.kirin.mydns.jp/sun-project/skill-mgr-api
    networks:
      - 'skill-mgr-system-net'
    ports:
      - '8081:8081'
networks:
  skill-mgr-system-net:
    driver: bridge
